[snowflake]
account = "dtdtbld-qw49305"
user = "STREAMLIT_SERVICE_USER"
role = "AIRFLOW_ROLE"
warehouse = "ELT_WH_S"
database = "ANALYTICS"
schema = "GOLD"

private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCObqw9hSGkqTEG
rPBcZ87HjqLc8ihSQedgufw4BYZXLkSFFhWH00ZOTcxSaXfzz7X+SoWHZq1sWs+f
ggGAD9itz0OUE5rTWwH9w69Yoj+izy17fflea5v5ZjkPXQVay3v9lrCV4P2hR/Rd
aRpVdEMFT74JxzUg2RZ3yoq9RwhgxgB1pOTfgzk3htuyB8eMVDJsnIpVqenf3Pe+
skejXRZM9DBZjKkP18UtSf9p9ViGhAPtWkpNKQPqpEXC7mIqE0UjSFR1lHtQSI7e
R0t0yzx+0saqSuG3d1e6iOnx+kPzADu1iQWxMB02JC2a4RT0wyHXPyqN7LmBWleo
l5xT6S6bAgMBAAECggEAMOg4tXEq4bcE8hVc/WXZv3UvYC24gbJGiFSkkfn3rKTi
+03fe8GksQuOvrefbDUk+VnOavVrVDsEcvF5oWcPkHMMceKfdbaYwvG4Gnev4TBB
nldd0rmhl6wtqKRYy9n2S9e77+MPRBuIgbCuzav7vW2pxALGr+5LBDwkkqS68DtZ
xKzNYwuUT/H4626sIluKAsqboyo29Ts8n4dleNWJveRCaks0s655y663kyIxL9z8
HetQ9JUZuTcU9cRTIx9Mh0uRHimY0hGQrdDXaeo0284Ci0bl9iyoiQxz37NtQjtc
CJuoLPJvUyGBYkJqgOZzrr+BNP5+QnQVdJgP34jfeQKBgQDFX5xfOrGa+7F14SHQ
71hOIhncxYv31Yufn/2kprdWBbhneP/pfanTN53u/R0/bnuugE6JrBGHmua4z0Y7
Z7mWJiPynFBJtcIcrPlsMhjsVRe3WkP21lOxmPDfr4l3IpcGhmWGtS63wIE/Fqz6
7yl3znjtg8iYrS/LJ6lRWe8RCQKBgQC4vU4o2fk+CyntvkqydwO5w4bu9HAf1cUO
k6OuQ3rllLuKGRk7DxGnPYAGUzGiizrQoRSdpLyzmdoF0tbp4BlsqPJ7e18/AK7b
RLkJhP0lqAuzS2RXGrHekijecW52dnQuvXBgp59meheTT9vtzLtqdn5sFcmyjORA
eFYH9CB/gwKBgBKOxNMnX5+k3rCotFdCydi+2BOr91ccGv6tOloK2t4Zt5bzB4za
pecYKZ9Y6TEXoEVuBvRm21cWt27U/lODky2M9IBRNjNYBaJQmTsVEsbV0V8J+63v
xPrD2JIPnSs4c17HsDAURQo97WkTJryJVCrRnQkoBOpmDkJZvk/J1vKRAoGBAKZd
vKRnX+Cy1wiGBOjg6xcAcWSB9vOEZJiy9oV5uZREs/syjRk1gdVVOhT4GMvjjIzT
cyhgcZtgIwp5jBdEPEExiGURfn3TVKScJ/Lds8eUpSzK6UrT/HiOsYVZK3w9QnXR
HgG9EnyL2O1NzqZBaEoA+erGWESWQvuYIwm4nQeXAoGABC63lH8vSs7yN9d7ddSP
YDzXe1JG4lBwoyZFEwG4vppZyIUy5ZR0az/VUInfUdBt6iDut01zAzaag2X8C6x5
VfjvJY4HyuMsqcR9lVTwZLmw6DiMh+Y/0D1CkGId+pzjuwiwxVRUSIw+CaxsD6ti
IXqAtZFktrBAr3P5umiSUAU=
-----END PRIVATE KEY-----
"""
