[snowflake]
account = "dtdtbld-qw49305"
user = "STREAMLIT_SERVICE_USER"
role = "AIRFLOW_ROLE"
warehouse = "ELT_WH_S"
database = "ANALYTICS"
schema = "GOLD"

private_key_path = "config/keys/snowflake_key.p8"
